#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
HOSTNAME_FILE="HOSTNAME"
HOSTNAME_FILE_PATH="$DOKKU_ROOT/$APP/$HOSTNAME_FILE"

if [[ -f "$HOSTNAME_FILE_PATH" ]] ; then
  output=$(head -n 1 $HOSTNAME_FILE_PATH)

  echo "$(cat)$output"
fi
